const translations = {
    "en": {
        "name": "English",
        "intro": "Arcane Merchant is a shop management simulation game set in the heart of a medieval fantasy realm. Explore the town, seize trade opportunities and begin your journey toward wealth. Enjoy cozy vibes as you trade, grow and build your dream shop. Every decision you make will shape your fortune and the future of your business.",
        "features": [
            "🛍️ Manage Your Store Establish and organize your own magical store, manage your inventory and fill your shelves with potions, magical weapons, mysterious crystals and a variety of fantastic artifacts. Strategize your displays to attract customers and ensure maximum profit.",
            "💰 Master the Art of Trade Adjust your prices dynamically based on supply and demand in the marketplace and manage your sales. With every successful deal, your wealth will grow rapidly and your reputation will spread throughout the realm. Earn the trust of your customers and adapt your trade strategies to their changing needs.",
            "🏰 Become the Wealthiest Merchant of the Kingdom Start from a humble stall; over time, expand and upgrade your store with new display areas. As your fame and fortune rise, work your way toward becoming the most respected and wealthiest merchant in town. Build your trading empire and take control of the economy of the Fantasy Middle Ages!",
            "🌿 Cozy and Relaxing Atmosphere Relax and grow your shop in a warm medieval fantasy world. Plan your trades and find your own pace. Enjoy the cozy vibes while you decide what to buy, what to sell and how to make your shop the best in town. There is no rush, but your choices still matter. Focus on building a successful business in a space where you can truly unwind."
        ]
    },
    "tr": {
        "name": "Turkish",
        "intro": "Arcane Merchant, orta çağ fantezi dünyasının kalbinde geçen bir dükkan yönetimi simülasyon oyunudur. Kasabayı keşfedin, ticaret fırsatlarını yakalayın ve zenginliğe giden yolculuğunuza başlayın. Ticaret yaparken, büyürken ve hayalinizdeki dükkanı inşa ederken huzurlu atmosferin tadını çıkarın. Vereceğiniz her karar, servetinizi ve işletmenizin geleceğini şekillendirecek.",
        "features": [
            "🛍️ Mağazanızı Yönetin Kendi büyülü mağazanızı kurun ve düzenleyin, envanterinizi yönetin ve raflarınızı iksirler, büyülü silahlar, gizemli kristaller ve çeşitli fantastik eserlerle doldurun. Müşterileri çekmek ve maksimum kar sağlamak için teşhir stratejilerinizi belirleyin.",
            "💰 Ticaret Sanatında Ustalaşın Fiyatlarınızı pazardaki arz ve talebe göre dinamik olarak ayarlayın ve satışlarınızı yönetin. Her başarılı anlaşmayla servetiniz hızla artacak ve itibarınız tüm diyara yayılacak. Müşterilerinizin güvenini kazanın ve ticaret stratejilerinizi onların değişen ihtiyaçlarına göre uyarlayın.",
            "🏰 Krallığın En Zengin Tüccarı Olun Mütevazı bir tezgahtan başlayın; zamanla mağazanızı yeni teşhir alanlarıyla genişletin ve geliştirin. Şöhretiniz ve servetiniz arttıkça, kasabanın en saygın ve en zengin tüccarı olma yolunda ilerleyin. Ticaret imparatorluğunuzu kurun ve Fantezi Orta Çağı'nın ekonomisinin kontrolünü elinize alın!",
            "🌿 Huzurlu ve Rahatlatıcı Atmosfer Sıcak bir orta çağ fantezi dünyasında rahatlayın ve dükkanınızı büyütün. Ticaretinizi planlayın ve kendi hızınızı bulun. Ne alacağınıza, ne satacağınıza ve dükkanınızı kasabanın en iyisi haline nasıl getireceğinize karar verirken huzurlu atmosferin tadını çıkarın. Acele yok, ancak seçimleriniz yine de önemli. Gerçekten rahatlayabileceğiniz bir alanda başarılı bir işletme kurmaya odaklanın."
        ]
    },
    "zh": {
        "name": "Chinese (Simplified)",
        "intro": "Arcane Merchant 是一款以中世纪奇幻王国为背景的商店管理模拟游戏。探索城镇，抓住贸易机会，开启你的致富之旅。在交易、成长和建立梦想商店的同时，享受舒适的氛围。你所做的每一个决定都将塑造你的财富和企业的未来。",
        "features": [
            "🛍️ 管理你的商店 建立并组织你自己的魔法商店，管理库存，并在货架上摆满药水、魔法武器、神秘水晶和各种奇幻文物。制定陈列策略以吸引顾客并确保最大利润。",
            "💰 掌握贸易艺术 根据市场供需动态调整价格并管理销售。随着每一笔成功的交易，你的财富将迅速增长，你的声誉将传遍整个王国。赢得顾客的信任，并根据他们不断变化的需求调整你的贸易策略。",
            "🏰 成为王国最富有的商人 从一个简陋的摊位开始；随着时间的推移，用新的展示区扩展和升级你的商店。随着名望和财富的增长，努力成为镇上最受尊敬和最富有的商人。建立你的贸易帝国，掌控中世纪奇幻世界的经济！",
            "🌿 舒适轻松的氛围 在温暖的中世纪奇幻世界中放松身心，通过经营发展你的商店。规划你的交易，找到属于你自己的节奏。在决定买什么、卖什么以及如何让你的商店成为镇上最好的商店时，享受舒适的氛围。没有匆忙，但你的选择依然重要。专注于在一个你可以真正放松的空间里建立成功的企业。"
        ]
    },
    "zh-TW": {
        "name": "Chinese (Traditional)",
        "intro": "Arcane Merchant 是一款以中世紀奇幻王國為背景的商店管理模擬遊戲。探索城鎮，抓住貿易機會，開啟您的致富之旅。在交易、成長和建立夢想商店的同時，享受舒適的氛圍。您所做的每一個決定都將塑造您的財富和企業的未來。",
        "features": [
            "🛍️ 管理您的商店 建立並組織您自己的魔法商店，管理庫存，並在貨架上擺滿藥水、魔法武器、神秘水晶和各種奇幻文物。制定陳列策略以吸引顧客並確保最大利潤。",
            "💰 掌握貿易藝術 根據市場供需動態調整價格並管理銷售。隨著每一筆成功的交易，您的財富將迅速增長，您的聲譽將傳遍整個王國。贏得顧客的信任，並根據他們不斷變化的需求調整您的貿易策略。",
            "🏰 成為王國最富有的商人 從一個簡陋的攤位開始；隨著時間的推移，用新的展示區擴展和升級您的商店。隨著名望和財富的增長，努力成為鎮上最受尊敬和最富有的商人。建立您的貿易帝國，掌控中世紀奇幻世界的經濟！",
            "🌿 舒適輕鬆的氛圍 在溫暖的中世紀奇幻世界中放鬆身心，透過經營發展您的商店。規劃您的交易，找到屬於您自己的節奏。在決定買什麼、賣什麼以及如何讓您的商店成為鎮上最好的商店時，享受舒適的氛圍。沒有匆忙，但您的選擇依然重要。專注於在一個您可以真正放鬆的空間裡建立成功的企業。"
        ]
    },
    "fr-FR": {
        "name": "French (France)",
        "intro": "Arcane Merchant est un jeu de simulation de gestion de boutique situé au cœur d'un royaume fantastique médiéval. Explorez la ville, saisissez les opportunités commerciales et commencez votre voyage vers la richesse. Profitez d'une ambiance chaleureuse tout en commerçant, en grandissant et en construisant la boutique de vos rêves. Chaque décision que vous prendrez façonnera votre fortune et l'avenir de votre entreprise.",
        "features": [
            "🛍️ Gérez Votre Magasin Établissez et organisez votre propre magasin magique, gérez votre inventaire et remplissez vos étagères de potions, d'armes magiques, de cristaux mystérieux et d'une variété d'artefacts fantastiques. Élaborez des stratégies pour vos présentoirs afin d'attirer les clients et d'assurer un profit maximum.",
            "💰 Maîtrisez l'Art du Commerce Ajustez vos prix de manière dynamique en fonction de l'offre et de la demande sur le marché et gérez vos ventes. Avec chaque transaction réussie, votre richesse augmentera rapidement et votre réputation se répandra dans tout le royaume. Gagnez la confiance de vos clients et adaptez vos stratégies commerciales à leurs besoins changeants.",
            "🏰 Devenez le Marchand le Plus Riche du Royaume Commencez par un modeste étal ; au fil du temps, agrandissez et améliorez votre magasin avec de nouvelles zones d'exposition. À mesure que votre renommée et votre fortune augmentent, progressez pour devenir le marchand le plus respecté et le plus riche de la ville. Bâtissez votre empire commercial et prenez le contrôle de l'économie du Moyen Âge Fantastique !",
            "🌿 Atmosphère Douillette et Relaxante Détendez-vous et développez votre boutique dans un monde fantastique médiéval chaleureux. Planifiez vos échanges et trouvez votre propre rythme. Profitez de l'ambiance douillette pendant que vous décidez quoi acheter, quoi vendre et comment faire de votre boutique la meilleure de la ville. Il n'y a pas d'urgence, mais vos choix comptent toujours. Concentrez-vous sur la création d'une entreprise prospère dans un espace où vous pouvez vraiment vous détendre."
        ]
    },
    "de": {
        "name": "German",
        "intro": "Arcane Merchant ist ein Ladenmanagement-Simulationsspiel, das im Herzen eines mittelalterlichen Fantasy-Reichs angesiedelt ist. Erkunde die Stadt, ergreife Handelsmöglichkeiten und beginne deine Reise zum Reichtum. Genieße die gemütliche Atmosphäre, während du handelst, wächst und deinen Traumladen aufbaust. Jede Entscheidung, die du triffst, wird dein Vermögen und die Zukunft deines Unternehmens prägen.",
        "features": [
            "🛍️ Verwalte deinen Laden Errichte und organisiere deinen eigenen magischen Laden, verwalte dein Inventar und fülle deine Regale mit Tränken, magischen Waffen, geheimnisvollen Kristallen und einer Vielzahl fantastischer Artefakte. Plane deine Auslagen strategisch, um Kunden anzuziehen und maximalen Gewinn zu erzielen.",
            "💰 Meistere die Kunst des Handels Passe deine Preise dynamisch an Angebot und Nachfrage auf dem Marktplatz an und verwalte deine Verkäufe. Mit jedem erfolgreichen Geschäft wird dein Reichtum schnell wachsen und dein Ruf wird sich im ganzen Reich verbreiten. Gewinne das Vertrauen deiner Kunden und passe deine Handelsstrategien an deren wechselnde Bedürfnisse an.",
            "🏰 Werde der reichste Händler des Königreichs Beginne mit einem bescheidenen Stand; im Laufe der Zeit erweitere und verbessere deinen Laden mit neuen Ausstellungsbereichen. Während dein Ruhm und dein Vermögen steigen, arbeite dich hoch, um der angesehenste und reichste Händler der Stadt zu werden. Baue dein Handelsimperium auf und übernimm die Kontrolle über die Wirtschaft des Fantasy-Mittelalters!",
            "🌿 Gemütliche und entspannende Atmosphäre Entspanne dich und lass deinen Laden in einer warmen mittelalterlichen Fantasy-Welt wachsen. Plane deine Geschäfte und finde dein eigenes Tempo. Genieße die gemütliche Stimmung, während du entscheidest, was du kaufen, was du verkaufen und wie du deinen Laden zum besten der Stadt machen willst. Es gibt keine Eile, aber deine Entscheidungen zählen trotzdem. Konzentriere dich darauf, ein erfolgreiches Geschäft in einem Raum aufzubauen, in dem du wirklich abschalten kannst."
        ]
    },
    "ja-JP": {
        "name": "Japanese (Japan)",
        "intro": "Arcane Merchantは、中世ファンタジー王国の中心を舞台にした店舗経営シミュレーションゲームです。街を探索し、商機を掴み、富への旅を始めましょう。居心地の良い雰囲気の中で、取引を行い、成長し、夢のお店を作り上げましょう。あなたの下すあらゆる決断が、あなたの財産とビジネスの未来を形作ります。",
        "features": [
            "🛍️ お店を経営しよう 自分だけの魔法のお店を設立して整理し、在庫を管理し、ポーション、魔法の武器、神秘的なクリスタル、そして様々な素晴らしいアーティファクトで棚を満たしましょう。陳列を工夫して顧客を引き付け、最大の利益を確保しましょう。",
            "💰 交易の技を極めよう 市場の需要と供給に基づいて価格を動的に調整し、売上を管理しましょう。取引が成功するたびに、あなたの富は急速に増え、あなたの評判は王国中に広まるでしょう。顧客の信頼を獲得し、変化するニーズに合わせて取引戦略を適応させましょう。",
            "🏰 王国で最も裕福な商人になろう 質素な露店から始めましょう。時間の経過とともに、新しい展示エリアでお店を拡張し、アップグレードしていきましょう。名声と富が高まるにつれて、街で最も尊敬され、最も裕福な商人になる道を進んでください。あなたの貿易帝国を築き、ファンタジー中世の経済を支配しましょう！",
            "🌿 居心地の良いリラックスできる雰囲気 暖かい中世ファンタジーの世界でリラックスしてお店を成長させましょう。取引を計画し、自分のペースを見つけましょう。何を買い、何を売り、どうすればあなたのお店を街一番にできるかを決めながら、居心地の良い雰囲気を楽しんでください。急ぐ必要はありませんが、あなたの選択は重要です。心からくつろげる空間で、成功するビジネスを築くことに集中しましょう。"
        ]
    },
    "ko": {
        "name": "Korean",
        "intro": "Arcane Merchant는 중세 판타지 왕국의 중심부를 배경으로 한 상점 경영 시뮬레이션 게임입니다. 마을을 탐험하고, 무역 기회를 포착하여 부를 향한 여정을 시작하세요. 아늑한 분위기 속에서 거래하고, 성장하며, 꿈의 상점을 건설해 보세요. 여러분이 내리는 모든 결정이 여러분의 재산과 사업의 미래를 결정할 것입니다.",
        "features": [
            "🛍️ 상점 관리 나만의 마법 상점을 설립하고 정리하며, 재고를 관리하고 선반을 물약, 마법 무기, 신비한 수정 및 다양한 환상적인 유물로 채우세요. 고객을 유치하고 최대 이익을 보장하기 위해 진열 전략을 세우세요.",
            "💰 무역의 기술 마스터 시장의 수요와 공급에 따라 가격을 역동적으로 조정하고 판매를 관리하세요. 성공적인 거래가 이루어질 때마다 여러분의 부는 빠르게 증가하고 명성은 왕국 전체로 퍼질 것입니다. 고객의 신뢰를 얻고 변화하는 고객의 요구에 맞춰 무역 전략을 조정하세요.",
            "🏰 왕국에서 가장 부유한 상인이 되세요 소박한 가판대에서 시작하여 시간이 지남에 따라 새로운 진열 공간으로 상점을 확장하고 업그레이드하세요. 명성과 부가 높아짐에 따라 마을에서 가장 존경받고 부유한 상인이 되기 위해 노력하세요. 무역 제국을 건설하고 판타지 중세 시대의 경제를 장악하세요!",
            "🌿 아늑하고 편안한 분위기 따뜻한 중세 판타지 세계에서 휴식을 취하며 상점을 성장시키세요. 거래를 계획하고 자신만의 속도를 찾으세요. 무엇을 사고, 무엇을 팔고, 어떻게 하면 마을 최고의 상점을 만들 수 있을지 결정하면서 아늑한 분위기를 즐기세요. 서두를 필요는 없지만, 여러분의 선택은 여전히 중요합니다. 진정으로 긴장을 풀 수 있는 공간에서 성공적인 사업을 구축하는 데 집중하세요."
        ]
    },
    "pl-PL": {
        "name": "Polish (Poland)",
        "intro": "Arcane Merchant to gra symulacyjna polegająca na zarządzaniu sklepem, osadzona w sercu średniowiecznego królestwa fantasy. Eksploruj miasto, wykorzystuj okazje handlowe i rozpocznij swoją podróż ku bogactwu. Ciesz się przytulną atmosferą, handlując, rozwijając się i budując swój wymarzony sklep. Każda podjęta przez ciebie decyzja ukształtuje twoją fortunę i przyszłość twojego biznesu.",
        "features": [
            "🛍️ Zarządzaj Swoim Sklepem Załóż i zorganizuj swój własny magiczny sklep, zarządzaj inwentarzem i wypełnij półki miksturami, magiczną bronią, tajemniczymi kryształami i różnorodnymi fantastycznymi artefaktami. Opracuj strategię ekspozycji, aby przyciągnąć klientów i zapewnić maksymalny zysk.",
            "💰 Opanuj Sztukę Handlu Dostosowuj ceny dynamicznie w oparciu o podaż i popyt na rynku oraz zarządzaj sprzedażą. Z każdą udaną transakcją twoje bogactwo będzie szybko rosnąć, a twoja reputacja rozprzestrzeni się po całym królestwie. Zdobądź zaufanie klientów i dostosuj strategie handlowe do ich zmieniających się potrzeb.",
            "🏰 Zostań Najbogatszym Kupcem w Królestwie Zacznij od skromnego straganu; z czasem rozbuduj i ulepsz swój sklep o nowe obszary wystawowe. W miarę wzrostu sławy i fortuny, pracuj nad tym, by stać się najbardziej szanowanym i najbogatszym kupcem w mieście. Zbuduj swoje imperium handlowe i przejmij kontrolę nad gospodarką Średniowiecznego Fantasy!",
            "🌿 Przytulna i Relaksująca Atmosfera Zrelaksuj się i rozwijaj swój sklep w ciepłym średniowiecznym świecie fantasy. Planuj swoje transakcje i znajdź własne tempo. Ciesz się przytulną atmosferą, decydując, co kupić, co sprzedać i jak sprawić, by twój sklep był najlepszy w mieście. Nie ma pośpiechu, ale twoje wybory wciąż mają znaczenie. Skup się na budowaniu odnoszącego sukcesy biznesu w przestrzeni, w której możesz naprawdę odpocząć."
        ]
    },
    "pt-BR": {
        "name": "Portuguese (Brazil)",
        "intro": "Arcane Merchant é um jogo de simulação de gerenciamento de loja ambientado no coração de um reino de fantasia medieval. Explore a cidade, aproveite as oportunidades comerciais e comece sua jornada rumo à riqueza. Desfrute de vibrações aconchegantes enquanto negocia, cresce e constrói a loja dos seus sonhos. Cada decisão que você tomar moldará sua fortuna e o futuro do seu negócio.",
        "features": [
            "🛍️ Gerencie Sua Loja Estabeleça e organize sua própria loja mágica, gerencie seu inventário e encha suas prateleiras com poções, armas mágicas, cristais misteriosos e uma variedade de artefatos fantásticos. Crie estratégias para suas exibições para atrair clientes e garantir o lucro máximo.",
            "💰 Domine a Arte do Comércio Ajuste seus preços dinamicamente com base na oferta e demanda do mercado e gerencie suas vendas. A cada negócio bem-sucedido, sua riqueza crescerá rapidamente e sua reputação se espalhará por todo o reino. Ganhe a confiança de seus clientes e adapte suas estratégias comerciais às necessidades em constante mudança deles.",
            "🏰 Torne-se o Comerciante Mais Rico do Reino Comece de uma banca humilde; com o tempo, expanda e melhore sua loja com novas áreas de exibição. À medida que sua fama e fortuna aumentam, trabalhe para se tornar o comerciante mais respeitado e rico da cidade. Construa seu império comercial e assuma o controle da economia da Idade Média de Fantasia!",
            "🌿 Atmosfera Aconchegante e Relaxante Relaxe e faça sua loja crescer em um mundo de fantasia medieval acolhedor. Planeje suas negociações e encontre seu próprio ritmo. Aproveite as vibrações aconchegantes enquanto decide o que comprar, o que vender e como tornar sua loja a melhor da cidade. Não há pressa, mas suas escolhas ainda importam. Concentre-se em construir um negócio de sucesso em um espaço onde você pode realmente relaxar."
        ]
    },
    "ru-RU": {
        "name": "Russian (Russia)",
        "intro": "Arcane Merchant — это игра-симулятор управления магазином, действие которой происходит в сердце средневекового фэнтезийного королевства. Исследуйте город, используйте торговые возможности и начните свой путь к богатству. Наслаждайтесь уютной атмосферой, торгуя, развиваясь и создавая магазин своей мечты. Каждое ваше решение будет определять ваше состояние и будущее вашего бизнеса.",
        "features": [
            "🛍️ Управляйте Своим Магазином Создайте и организуйте свой собственный волшебный магазин, управляйте инвентарем и заполняйте полки зельями, магическим оружием, таинственными кристаллами и множеством фантастических артефактов. Продумывайте стратегию размещения товаров, чтобы привлечь клиентов и обеспечить максимальную прибыль.",
            "💰 Овладейте Искусством Торговли Динамически корректируйте цены в зависимости от спроса и предложения на рынке и управляйте продажами. С каждой успешной сделкой ваше богатство будет быстро расти, а ваша репутация распространится по всему королевству. Завоюйте доверие клиентов и адаптируйте свои торговые стратегии к их меняющимся потребностям.",
            "🏰 Станьте Самым Богатым Купцом Королевства Начните со скромного прилавка; со временем расширяйте и улучшайте свой магазин новыми торговыми зонами. По мере роста вашей славы и состояния, стремитесь стать самым уважаемым и богатым торговцем в городе. Постройте свою торговую империю и возьмите под контроль экономику Фэнтезийного Средневековья!",
            "🌿 Уютная и Расслабляющая Атмосфера Расслабьтесь и развивайте свой магазин в теплом мире средневекового фэнтези. Планируйте свои сделки и найдите свой собственный темп. Наслаждайтесь уютной атмосферой, решая, что покупать, что продавать и как сделать свой магазин лучшим в городе. Спешить некуда, но ваш выбор все равно имеет значение. Сосредоточьтесь на создании успешного бизнеса в пространстве, где вы можете по-настоящему отдохнуть."
        ]
    },
    "es-ES": {
        "name": "Spanish (Spain)",
        "intro": "Arcane Merchant es un juego de simulación de gestión de tiendas ambientado en el corazón de un reino de fantasía medieval. Explora la ciudad, aprovecha las oportunidades comerciales y comienza tu viaje hacia la riqueza. Disfruta de un ambiente acogedor mientras comercias, creces y construyes la tienda de tus sueños. Cada decisión que tomes dará forma a tu fortuna y al futuro de tu negocio.",
        "features": [
            "🛍️ Gestiona Tu Tienda Establece y organiza tu propia tienda mágica, gestiona tu inventario y llena tus estanterías con pociones, armas mágicas, cristales misteriosos y una variedad de artefactos fantásticos. Estrategiza tus exhibiciones para atraer clientes y asegurar el máximo beneficio.",
            "💰 Domina el Arte del Comercio Ajusta tus precios dinámicamente basándote en la oferta y la demanda del mercado y gestiona tus ventas. Con cada trato exitoso, tu riqueza crecerá rápidamente y tu reputación se extenderá por todo el reino. Gánate la confianza de tus clientes y adapta tus estrategias comerciales a sus necesidades cambiantes.",
            "🏰 Conviértete en el Comerciante Más Rico del Reino Empieza desde un humilde puesto; con el tiempo, expande y mejora tu tienda con nuevas áreas de exhibición. A medida que tu fama y fortuna aumenten, trabaja para convertirte en el comerciante más respetado y rico de la ciudad. ¡Construye tu imperio comercial y toma el control de la economía de la Edad Media de Fantasía!",
            "🌿 Atmósfera Acogedora y Relajante Relájate y haz crecer tu tienda en un cálido mundo de fantasía medieval. Planifica tus comercios y encuentra tu propio ritmo. Disfruta del ambiente acogedor mientras decides qué comprar, qué vender y cómo hacer que tu tienda sea la mejor de la ciudad. No hay prisa, pero tus elecciones siguen importando. Concéntrate en construir un negocio exitoso en un espacio donde realmente puedas desconectar."
        ]
    },
    "it-IT": {
        "name": "Italian (Italy)",
        "intro": "Arcane Merchant è un gioco di simulazione gestionale ambientato nel cuore di un regno fantasy medievale. Esplora la città, cogli le opportunità commerciali e inizia il tuo viaggio verso la ricchezza. Goditi un'atmosfera accogliente mentre commerci, cresci e costruisci il negozio dei tuoi sogni. Ogni decisione che prenderai plasmerà la tua fortuna e il futuro della tua attività.",
        "features": [
            "🛍️ Gestisci il Tuo Negozio Fonda e organizza il tuo negozio magico, gestisci il tuo inventario e riempi gli scaffali con pozioni, armi magiche, cristalli misteriosi e una varietà di artefatti fantastici. Strategizza le tue esposizioni per attirare i clienti e garantire il massimo profitto.",
            "💰 Padroneggia l'Arte del Commercio Regola i tuoi prezzi dinamicamente in base alla domanda e all'offerta nel mercato e gestisci le tue vendite. Con ogni affare di successo, la tua ricchezza crescerà rapidamente e la tua reputazione si diffonderà in tutto il regno. Guadagna la fiducia dei tuoi clienti e adatta le tue strategie commerciali alle loro mutevoli esigenze.",
            "🏰 Diventa il Mercante Più Ricco del Regno Inizia da un'umile bancarella; col tempo, espandi e migliora il tuo negozio con nuove aree espositive. Man mano che la tua fama e la tua fortuna aumentano, lavora per diventare il mercante più rispettato e ricco della città. Costruisci il tuo impero commerciale e prendi il controllo dell'economia del Medioevo Fantasy!",
            "🌿 Atmosfera Accogliente e Rilassante Rilassati e fai crescere il tuo negozio in un caldo mondo fantasy medievale. Pianifica i tuoi scambi e trova il tuo ritmo. Goditi le vibrazioni accoglienti mentre decidi cosa comprare, cosa vendere e come rendere il tuo negozio il migliore della città. Non c'è fretta, ma le tue scelte contano comunque. Concentrati sulla costruzione di un'attività di successo in uno spazio in cui puoi davvero rilassarti."
        ]
    },
    "id-ID": {
        "name": "Indonesian (Indonesia)",
        "intro": "Arcane Merchant adalah game simulasi manajemen toko yang berlatar di jantung kerajaan fantasi abad pertengahan. Jelajahi kota, raih peluang dagang, dan mulailah perjalanan Anda menuju kekayaan. Nikmati suasana nyaman saat Anda berdagang, tumbuh, dan membangun toko impian Anda. Setiap keputusan yang Anda buat akan membentuk nasib Anda dan masa depan bisnis Anda.",
        "features": [
            "🛍️ Kelola Toko Anda Dirikan dan atur toko ajaib Anda sendiri, kelola inventaris, dan isi rak Anda dengan ramuan, senjata ajaib, kristal misterius, dan berbagai artefak fantastis. Atur strategi tampilan Anda untuk menarik pelanggan dan memastikan keuntungan maksimal.",
            "💰 Kuasai Seni Berdagang Sesuaikan harga Anda secara dinamis berdasarkan penawaran dan permintaan di pasar dan kelola penjualan Anda. Dengan setiap kesepakatan yang sukses, kekayaan Anda akan tumbuh pesat dan reputasi Anda akan menyebar ke seluruh kerajaan. Dapatkan kepercayaan pelanggan Anda dan sesuaikan strategi perdagangan Anda dengan kebutuhan mereka yang berubah.",
            "🏰 Menjadi Pedagang Terkaya di Kerajaan Mulailah dari kios sederhana; seiring waktu, perluas dan tingkatkan toko Anda dengan area tampilan baru. Seiring ketenaran dan kekayaan Anda meningkat, berusahalah untuk menjadi pedagang yang paling dihormati dan terkaya di kota. Bangun kerajaan dagang Anda dan ambil kendali ekonomi Abad Pertengahan Fantasi!",
            "🌿 Suasana Nyaman dan Santai Bersantai dan kembangkan toko Anda di dunia fantasi abad pertengahan yang hangat. Rencanakan perdagangan Anda dan temukan ritme Anda sendiri. Nikmati suasana nyaman saat Anda memutuskan apa yang akan dibeli, apa yang akan dijual, dan bagaimana menjadikan toko Anda yang terbaik di kota. Tidak perlu terburu-buru, tetapi pilihan Anda tetap penting. Fokuslah untuk membangun bisnis yang sukses di ruang di mana Anda dapat benar-benar bersantai."
        ]
    },
    "vi-VN": {
        "name": "Vietnamese (Vietnam)",
        "intro": "Arcane Merchant là một trò chơi mô phỏng quản lý cửa hàng lấy bối cảnh tại trung tâm của một vương quốc giả tưởng thời trung cổ. Khám phá thị trấn, nắm bắt cơ hội giao thương và bắt đầu hành trình làm giàu của bạn. Tận hưởng bầu không khí ấm cúng khi bạn buôn bán, phát triển và xây dựng cửa hàng mơ ước của mình. Mọi quyết định bạn đưa ra sẽ định hình vận mệnh và tương lai doanh nghiệp của bạn.",
        "features": [
            "🛍️ Quản Lý Cửa Hàng Của Bạn Thiết lập và tổ chức cửa hàng ma thuật của riêng bạn, quản lý kho hàng và lấp đầy các kệ hàng bằng thuốc độc, vũ khí ma thuật, tinh thể bí ẩn và nhiều loại hiện vật tuyệt vời. Lên chiến lược trưng bày để thu hút khách hàng và đảm bảo lợi nhuận tối đa.",
            "💰 Nắm Vững Nghệ Thuật Buôn Bán Điều chỉnh giá cả một cách linh hoạt dựa trên cung và cầu trên thị trường và quản lý doanh số bán hàng của bạn. Với mỗi giao dịch thành công, sự giàu có của bạn sẽ tăng lên nhanh chóng và danh tiếng của bạn sẽ lan rộng khắp vương quốc. Giành được lòng tin của khách hàng và điều chỉnh chiến lược buôn bán của bạn theo nhu cầu thay đổi của họ.",
            "🏰 Trở Thành Thương Nhân Giàu Có Nhất Vương Quốc Bắt đầu từ một gian hàng khiêm tốn; theo thời gian, hãy mở rộng và nâng cấp cửa hàng của bạn với các khu vực trưng bày mới. Khi danh tiếng và tài sản của bạn tăng lên, hãy nỗ lực để trở thành thương nhân được kính trọng và giàu có nhất trong thị trấn. Xây dựng đế chế thương mại của bạn và nắm quyền kiểm soát nền kinh tế của Thời Trung Cổ Giả Tưởng!",
            "🌿 Bầu Không Khí Ấm Cúng và Thư Giãn Thư giãn và phát triển cửa hàng của bạn trong một thế giới giả tưởng thời trung cổ ấm áp. Lên kế hoạch cho các giao dịch và tìm ra nhịp độ của riêng bạn. Tận hưởng những rung cảm ấm cúng trong khi bạn quyết định mua gì, bán gì và làm thế nào để biến cửa hàng của mình trở thành cửa hàng tốt nhất trong thị trấn. Không cần phải vội vã, nhưng những lựa chọn của bạn vẫn rất quan trọng. Tập trung vào việc xây dựng một doanh nghiệp thành công trong một không gian mà bạn có thể thực sự thư giãn."
        ]
    },
    "th-TH": {
        "name": "Thai (Thailand)",
        "intro": "Arcane Merchant เป็นเกมจำลองการบริหารจัดการร้านค้าที่ตั้งอยู่ในใจกลางของอาณาจักรแฟนตาซียุคกลาง สำรวจเมือง คว้าโอกาสทางการค้า และเริ่มต้นการเดินทางสู่ความมั่งคั่ง เพลิดเพลินไปกับบรรยากาศที่แสนอบอุ่นในขณะที่คุณทำการค้า เติบโต และสร้างร้านค้าในฝันของคุณ ทุกการตัดสินใจของคุณจะกำหนดโชคชะตาและอนาคตของธุรกิจคุณ",
        "features": [
            "🛍️ จัดการร้านค้าของคุณ ก่อตั้งและจัดระเบียบร้านเวทมนตร์ของคุณเอง จัดการสินค้าคงคลัง และเติมเต็มชั้นวางของคุณด้วยน้ำยา อาวุธเวทมนตร์ คริสตัลลึกลับ และสิ่งประดิษฐ์มหัศจรรย์หลากหลายชนิด วางกลยุทธ์การจัดแสดงสินค้าเพื่อดึงดูดลูกค้าและรับประกันผลกำไรสูงสุด",
            "💰 เชี่ยวชาญศิลปะการค้า ปรับราคาของคุณแบบไดนามิกตามอุปสงค์และอุปทานในตลาดและจัดการการขายของคุณ ด้วยทุกข้อตกลงที่ประสบความสำเร็จ ความมั่งคั่งของคุณจะเติบโตอย่างรวดเร็วและชื่อเสียงของคุณจะแพร่กระจายไปทั่วอาณาจักร ได้รับความไว้วางใจจากลูกค้าและปรับกลยุทธ์การค้าของคุณให้เข้ากับความต้องการที่เปลี่ยนแปลงไปของพวกเขา",
            "🏰 ก้าวเป็นพ่อค้าที่ร่ำรวยที่สุดในอาณาจักร เริ่มต้นจากแผงขายของเล็กๆ เมื่อเวลาผ่านไป ขยายและอัปเกรดร้านค้าของคุณด้วยพื้นที่จัดแสดงใหม่ๆ เมื่อชื่อเสียงและความมั่งคั่งของคุณเพิ่มขึ้น จงมุ่งมั่นที่จะเป็นพ่อค้าที่ได้รับการเคารพและร่ำรวยที่สุดในเมือง สร้างจักรวรรดิการค้าของคุณและเข้าควบคุมเศรษฐกิจของยุคกลางแฟนตาซี!",
            "🌿 บรรยากาศที่อบอุ่นและผ่อนคลาย ผ่อนคลายและพัฒนาร้านค้าของคุณในโลกแฟนตาซียุคกลางที่อบอุ่น วางแผนการค้าของคุณและค้นหาจังหวะของตัวเอง เพลิดเพลินไปกับบรรยากาศที่แสนสบายในขณะที่คุณตัดสินใจว่าจะซื้ออะไร ขายอะไร และจะทำให้ร้านของคุณเป็นร้านที่ดีที่สุดในเมืองได้อย่างไร ไม่มีความรีบร้อน แต่ทางเลือกของคุณยังคงมีความสำคัญ มุ่งเน้นไปที่การสร้างธุรกิจที่ประสบความสำเร็จในพื้นที่ที่คุณสามารถผ่อนคลายได้อย่างแท้จริง"
        ]
    },
    "ar-SA": {
        "name": "Arabic (Saudi Arabia)",
        "intro": "Arcane Merchant هي لعبة محاكاة لإدارة المتاجر تدور أحداثها في قلب مملكة خيالية من العصور الوسطى. استكشف المدينة، واغتنم الفرص التجارية وابدأ رحلتك نحو الثراء. استمتع بالأجواء المريحة بينما تتاجر وتنمو وتبني متجر أحلامك. كل قرار تتخذه سيشكل ثروتك ومستقبل عملك.",
        "features": [
            "🛍️ أدر متجرك أنشئ ونظم متجرك السحري الخاص، وأدر مخزونك واملأ أرففك بالجرعات والأسلحة السحرية والبلورات الغامضة ومجموعة متنوعة من القطع الأثرية الرائعة. ضع استراتيجية لعروضك لجذب العملاء وضمان أقصى ربح.",
            "💰 أتقن فن التجارة عدل أسعارك ديناميكيًا بناءً على العرض والطلب في السوق وأدر مبيعاتك. مع كل صفقة ناجحة، ستنمو ثروتك بسرعة وستنتشر سمعتك في جميع أنحاء المملكة. اكسب ثقة عملائك وقم بتكييف استراتيجيات التجارة الخاصة بك مع احتياجاتهم المتغيرة.",
            "🏰 كن أغنى تاجر في المملكة ابدأ من كشك متواضع؛ بمرور الوقت، قم بتوسيع وتحديث متجرك بمناطق عرض جديدة. مع ارتفاع شهرتك وثروتك، شق طريقك لتصبح التاجر الأكثر احترامًا وثراءً في المدينة. ابن إمبراطوريتك التجارية وسيطر على اقتصاد العصور الوسطى الخيالية!",
            "🌿 جو مريح ومريح استرخ وقم بتنمية متجرك في عالم خيالي دافئ من العصور الوسطى. خطط لتداولاتك واعثر على وتيرتك الخاصة. استمتع بالأجواء المريحة بينما تقرر ما ستشتريه وما ستبيعه وكيف تجعل متجرك الأفضل في المدينة. ليس هناك عجلة من أمرك، لكن خياراتك لا تزال مهمة. ركز على بناء عمل ناجح في مساحة يمكنك فيها الاسترخاء حقًا."
        ]
    },
    "hi-IN": {
        "name": "Hindi (India)",
        "intro": "Arcane Merchant मध्ययुगीन फंतासी साम्राज्य के केंद्र में स्थित एक दुकान प्रबंधन सिमुलेशन गेम है। शहर का पता लगाएं, व्यापार के अवसरों को भुनाएं और धन की ओर अपनी यात्रा शुरू करें। व्यापार करते समय, बढ़ते हुए और अपने सपनों की दुकान बनाते समय आरामदायक वाइब्स का आनंद लें। आपके द्वारा लिया गया हर निर्णय आपके भाग्य और आपके व्यवसाय के भविष्य को आकार देगा।",
        "features": [
            "🛍️ अपनी दुकान का प्रबंधन करें अपनी खुद की जादुई दुकान स्थापित करें और व्यवस्थित करें, अपनी इन्वेंट्री का प्रबंधन करें और अपनी अलमारियों को औषधि, जादुई हथियार, रहस्यमय क्रिस्टल और विभिन्न प्रकार की शानदार कलाकृतियों से भरें। ग्राहकों को आकर्षित करने और अधिकतम लाभ सुनिश्चित करने के लिए अपने प्रदर्शन की रणनीति बनाएं।",
            "💰 व्यापार की कला में महारत हासिल करें बाजार में आपूर्ति और मांग के आधार पर अपनी कीमतों को गतिशील रूप से समायोजित करें और अपनी बिक्री का प्रबंधन करें। हर सफल सौदे के साथ, आपकी संपत्ति तेजी से बढ़ेगी और आपकी प्रतिष्ठा पूरे राज्य में फैल जाएगी। अपने ग्राहकों का विश्वास जीतें और अपनी व्यापार रणनीतियों को उनकी बदलती जरूरतों के अनुसार अपनाएं।",
            "🏰 राज्य के सबसे अमीर व्यापारी बनें एक विनम्र स्टाल से शुरू करें; समय के साथ, नए प्रदर्शन क्षेत्रों के साथ अपनी दुकान का विस्तार और उन्नयन करें। जैसे-जैसे आपकी प्रसिद्धि और भाग्य बढ़ता है, शहर में सबसे सम्मानित और सबसे अमीर व्यापारी बनने की दिशा में काम करें। अपना व्यापारिक साम्राज्य बनाएं और काल्पनिक मध्य युग की अर्थव्यवस्था पर नियंत्रण रखें!",
            "🌿 आरामदायक और आरामदेह माहौल एक गर्म मध्ययुगीन फंतासी दुनिया में आराम करें और अपनी दुकान बढ़ाएं। अपने व्यापार की योजना बनाएं और अपनी गति पाएं। आरामदायक वाइब्स का आनंद लें जब आप तय करते हैं कि क्या खरीदना है, क्या बेचना है और अपनी दुकान को शहर में सबसे अच्छा कैसे बनाना है। कोई जल्दबाजी नहीं है, लेकिन आपकी पसंद अभी भी मायने रखती है। एक ऐसी जगह में एक सफल व्यवसाय बनाने पर ध्यान केंद्रित करें जहां आप वास्तव में आराम कर सकें।"
        ]
    },
    "es-419": {
        "name": "Spanish (Latin America)",
        "intro": "Arcane Merchant es un juego de simulación de gestión de tiendas ambientado en el corazón de un reino de fantasía medieval. Explora la ciudad, aprovecha las oportunidades comerciales y comienza tu viaje hacia la riqueza. Disfruta de un ambiente acogedor mientras comercias, creces y construyes la tienda de tus sueños. Cada decisión que tomes dará forma a tu fortuna y al futuro de tu negocio.",
        "features": [
            "🛍️ Gestiona Tu Tienda Establece y organiza tu propia tienda mágica, gestiona tu inventario y llena tus estanterías con pociones, armas mágicas, cristales misteriosos y una variedad de artefactos fantásticos. Estrategiza tus exhibiciones para atraer clientes y asegurar el máximo beneficio.",
            "💰 Domina el Arte del Comercio Ajusta tus precios dinámicamente basándote en la oferta y la demanda del mercado y gestiona tus ventas. Con cada trato exitoso, tu riqueza crecerá rápidamente y tu reputación se extenderá por todo el reino. Gánate la confianza de tus clientes y adapta tus estrategias comerciales a sus necesidades cambiantes.",
            "🏰 Conviértete en el Comerciante Más Rico del Reino Empieza desde un humilde puesto; con el tiempo, expande y mejora tu tienda con nuevas áreas de exhibición. A medida que tu fama y fortuna aumenten, trabaja para convertirte en el comerciante más respetado y rico de la ciudad. ¡Construye tu imperio comercial y toma el control de la economía de la Edad Media de Fantasía!",
            "🌿 Atmósfera Acogedora y Relajante Relájate y haz crecer tu tienda en un cálido mundo de fantasía medieval. Planifica tus comercios y encuentra tu propio ritmo. Disfruta del ambiente acogedor mientras decides qué comprar, qué vender y cómo hacer que tu tienda sea la mejor de la ciudad. No hay prisa, pero tus elecciones siguen importando. Concéntrate en construir un negocio exitoso en un espacio donde realmente puedas desconectar."
        ]
    },
    "nl-NL": {
        "name": "Dutch (Netherlands)",
        "intro": "Arcane Merchant is een simulatiespel voor winkelbeheer dat zich afspeelt in het hart van een middeleeuws fantasierijk. Verken de stad, grijp handelsmogelijkheden en begin je reis naar rijkdom. Geniet van de gezellige sfeer terwijl je handelt, groeit en je droomwinkel bouwt. Elke beslissing die je neemt, zal je fortuin en de toekomst van je bedrijf bepalen.",
        "features": [
            "🛍️ Beheer Je Winkel Vestig en organiseer je eigen magische winkel, beheer je voorraad en vul je planken met drankjes, magische wapens, mysterieuze kristallen en een verscheidenheid aan fantastische artefacten. Bepaal de strategie voor je displays om klanten aan te trekken en maximale winst te garanderen.",
            "💰 Beheers de Kunst van het Handelen Pas je prijzen dynamisch aan op basis van vraag en aanbod op de markt en beheer je verkopen. Bij elke succesvolle deal zal je rijkdom snel groeien en je reputatie zich door het hele rijk verspreiden. Win het vertrouwen van je klanten en pas je handelsstrategieën aan hun veranderende behoeften aan.",
            "🏰 Word de Rijkste Koopman van het Koninkrijk Begin met een bescheiden kraampje; breid na verloop van tijd je winkel uit en upgrade deze met nieuwe displayruimtes. Naarmate je roem en fortuin stijgen, werk je je omhoog om de meest gerespecteerde en rijkste koopman in de stad te worden. Bouw je handelsimperium op en neem de controle over de economie van de Fantasy Middeleeuwen!",
            "🌿 Gezellige en Ontspannende Sfeer Ontspan en laat je winkel groeien in een warme middeleeuwse fantasiewereld. Plan je transacties en vind je eigen tempo. Geniet van de gezellige vibes terwijl je beslist wat je wilt kopen, wat je wilt verkopen en hoe je je winkel de beste van de stad kunt maken. Er is geen haast, maar je keuzes doen er nog steeds toe. Richt je op het opbouwen van een succesvol bedrijf in een ruimte waar je echt tot rust kunt komen."
        ]
    },
    "cs-CZ": {
        "name": "Czech (Czech Republic)",
        "intro": "Arcane Merchant je simulační hra pro správu obchodu zasazená do srdce středověké fantasy říše. Prozkoumejte město, využijte obchodní příležitosti a vydejte se na cestu k bohatství. Užijte si útulnou atmosféru, zatímco obchodujete, rostete a budujete svůj vysněný obchod. Každé vaše rozhodnutí bude formovat vaše jmění a budoucnost vašeho podnikání.",
        "features": [
            "🛍️ Spravujte Svůj Obchod Založte a zorganizujte svůj vlastní magický obchod, spravujte své zásoby a naplňte své regály lektvary, magickými zbraněmi, tajemnými krystaly a řadou fantastických artefaktů. Strategicky plánujte své výlohy, abyste přilákali zákazníky a zajistili maximální zisk.",
            "💰 Ovládněte Umění Obchodu Dynamicky upravujte své ceny na základě nabídky a poptávky na trhu a řiďte své prodeje. S každým úspěšným obchodem bude vaše bohatství rychle růst a vaše pověst se rozšíří po celé říši. Získejte důvěru svých zákazníků a přizpůsobte své obchodní strategie jejich měnícím se potřebám.",
            "🏰 Staňte se Nejbohatším Obchodníkem Království Začněte od skromného stánku; postupem času rozšiřujte a vylepšujte svůj obchod o nové výstavní prostory. Jak vaše sláva a jmění porostou, pracujte na tom, abyste se stali nejuznávanějším a nejbohatším obchodníkem ve městě. Vybudujte své obchodní impérium a převezměte kontrolu nad ekonomikou Fantasy Středověku!",
            "🌿 Útulná a Relaxační Atmosféra Odpočiňte si a rozvíjejte svůj obchod v teplém středověkém fantasy světě. Plánujte své obchody a najděte si své vlastní tempo. Užijte si útulnou atmosféru, zatímco se rozhodujete, co koupit, co prodat a jak udělat svůj obchod nejlepším ve městě. Není kam spěchat, ale na vašich volbách stále záleží. Zaměřte se na budování úspěšného podnikání v prostoru, kde si můžete skutečně odpočinout."
        ]
    },
    "uk-UA": {
        "name": "Ukrainian (Ukraine)",
        "intro": "Arcane Merchant — це гра-симулятор управління магазином, дія якої розгортається в серці середньовічного фентезійного королівства. Досліджуйте місто, використовуйте торгові можливості та почніть свою подорож до багатства. Насолоджуйтесь затишною атмосферою, торгуючи, розвиваючись і будуючи магазин своєї мрії. Кожне ваше рішення формуватиме ваші статки та майбутнє вашого бізнесу.",
        "features": [
            "🛍️ Керуйте Своїм Магазином Створіть та організуйте свій власний магічний магазин, керуйте інвентарем і заповнюйте полиці зіллям, магічною зброєю, таємничими кристалами та різноманітними фантастичними артефактами. Продумуйте стратегію розміщення товарів, щоб залучити клієнтів і забезпечити максимальний прибуток.",
            "💰 Опануйте Мистецтво Торгівлі Динамічно регулюйте ціни залежно від попиту та пропозиції на ринку та керуйте своїми продажами. З кожною успішною угодою ваше багатство швидко зростатиме, а ваша репутація поширюватиметься по всьому королівству. Завоюйте довіру клієнтів і адаптуйте свої торгові стратегії до їхніх потреб, що змінюються.",
            "🏰 Станьте Найбагатшим Купцем Королівства Почніть зі скромного прилавка; з часом розширюйте та покращуйте свій магазин новими торговими зонами. У міру зростання вашої слави та статків прагніть стати найбільш шанованим і найбагатшим торговцем у місті. Побудуйте свою торгову імперію та візьміть під контроль економіку Фентезійного Середньовіччя!",
            "🌿 Затишна та Розслаблююча Атмосфера Розслабтеся та розвивайте свій магазин у теплому світі середньовічного фентезі. Плануйте свої угоди та знайдіть свій власний темп. Насолоджуйтесь затишною атмосферою, вирішуючи, що купувати, що продавати та як зробити свій магазин найкращим у місті. Поспішати нікуди, але ваш вибір все одно має значення. Зосередьтеся на побудові успішного бізнесу в просторі, де ви можете по-справжньому відпочити."
        ]
    },
    "sv-SE": {
        "name": "Swedish (Sweden)",
        "intro": "Arcane Merchant är ett butikshanteringssimuleringsspel som utspelar sig i hjärtat av ett medeltida fantasyrike. Utforska staden, ta vara på handelsmöjligheter och påbörja din resa mot rikedom. Njut av mysiga vibbar medan du handlar, växer och bygger din drömbutik. Varje beslut du fattar kommer att forma din förmögenhet och framtiden för ditt företag.",
        "features": [
            "🛍️ Hantera Din Butik Etablera och organisera din egen magiska butik, hantera ditt lager och fyll dina hyllor med drycker, magiska vapen, mystiska kristaller och en mängd fantastiska artefakter. Strategisera dina skyltningar för att locka kunder och säkerställa maximal vinst.",
            "💰 Bemästra Handelns Konst Justera dina priser dynamiskt baserat på tillgång och efterfrågan på marknaden och hantera din försäljning. Med varje framgångsrik affär kommer din rikedom att växa snabbt och ditt rykte kommer att spridas över hela riket. Förtjäna dina kunders förtroende och anpassa dina handelsstrategier efter deras föränderliga behov.",
            "🏰 Bli Kungarikets Rikaste Köpman Börja från ett ödmjukt stånd; med tiden, expandera och uppgradera din butik med nya visningsområden. I takt med att din berömmelse och förmögenhet ökar, arbeta dig uppåt för att bli den mest respekterade och rikaste köpmannen i staden. Bygg ditt handelsimperium och ta kontroll över ekonomin i Fantasy-medeltiden!",
            "🌿 Mysig och Avkopplande Atmosfär Koppla av och få din butik att växa i en varm medeltida fantasyvärld. Planera dina affärer och hitta din egen takt. Njut av den mysiga stämningen medan du bestämmer vad du ska köpa, vad du ska sälja och hur du ska göra din butik till den bästa i staden. Det är ingen brådska, men dina val spelar fortfarande roll. Fokusera på att bygga ett framgångsrikt företag i ett utrymme där du verkligen kan varva ner."
        ]
    },
    "el-GR": {
        "name": "Greek (Greece)",
        "intro": "Το Arcane Merchant είναι un παιχνίδι προσομοίωσης διαχείρισης καταστήματος που διαδραματίζεται στην καρδιά ενός μεσαιωνικού βασιλείου φαντασίας. Εξερευνήστε την πόλη, αρπάξτε εμπορικές ευκαιρίες και ξεκινήστε το ταξίδι σας προς τον πλούτο. Απολαύστε τη ζεστή ατμόσφαιρα καθώς κάνετε εμπόριο, αναπτύσσεστε και χτίζετε το κατάστημα των ονείρων σας. Κάθε απόφαση που παίρνετε θα διαμορφώσει την περιουσία σας και το μέλλον της επιχείρησής σας.",
        "features": [
            "🛍️ Διαχειριστείτε το Κατάστημά Σας Ιδρύστε και οργανώστε το δικό σας μαγικό κατάστημα, διαχειριστείτε το απόθεμά σας και γεμίστε τα ράφια σας με φίλτρα, μαγικά όπλα, μυστηριώδεις κρυστάλλους και μια ποικιλία φανταστικών αντικειμένων. Σχεδιάστε στρατηγικά τις βιτρίνες σας για να προσελκύσετε πελάτες και να εξασφαλίσετε το μέγιστο κέρδος.",
            "💰 Κατακτήστε την Τέχνη του Εμπορίου Προσαρμόστε τις τιμές σας δυναμικά με βάση την προσφορά και τη ζήτηση στην αγορά και διαχειριστείτε τις πωλήσεις σας. Με κάθε επιτυχημένη συμφωνία, ο πλούτος σας θα αυξάνεται γρήγορα και η φήμη σας θα εξαπλώνεται σε όλο το βασίλειο. Κερδίστε την εμπιστοσύνη των πελατών σας και προσαρμόστε τις εμπορικές στρατηγικές σας στις μεταβαλλόμενες ανάγκες τους.",
            "🏰 Γίνετε ο Πλουσιότερος Έμπορος του Βασιλείου Ξεκινήστε από έναν ταπεινό πάγκο. με την πάροδο του χρόνου, επεκτείνετε και αναβαθμίστε το κατάστημά σας με νέους χώρους έκθεσης. Καθώς η φήμη και η περιουσία σας αυξάνονται, εργαστείτε για να γίνετε ο πιο σεβαστός και πλούσιος έμπορος στην πόλη. Χτίστε την εμπορική σας αυτοκρατορία και πάρτε τον έλεγχο της οικονομίας του Μεσαίωνα Φαντασίας!",
            "🌿 Ζεστή και Χαλαρωτική Ατμόσφαιρα Χαλαρώστε και αναπτύξτε το κατάστημά σας σε έναν ζεστό μεσαιωνικό κόσμο φαντασίας. Σχεδιάστε τις συναλλαγές σας και βρείτε τον δικό σας ρυθμό. Απολαύστε τη ζεστή ατμόσφαιρα καθώς αποφασίζετε τι θα αγοράσετε, τι θα πουλήσετε και πώς θα κάνετε το κατάστημά σας το καλύτερο στην πόλη. Δεν υπάρχει βιασύνη, αλλά οι επιλογές σας εξακολουθούν να έχουν σημασία. Εστιάστε στο χτίσιμο μιας επιτυχημένης επιχείρησης σε έναν χώρο όπου μπορείτε πραγματικά να χαλαρώσετε."
        ]
    },
    "ro-RO": {
        "name": "Romanian (Romania)",
        "intro": "Arcane Merchant este un joc de simulare a gestionării magazinului, amplasat în inima unui tărâm fantastic medieval. Explorează orașul, profită de oportunitățile comerciale și începe-ți călătoria către bogăție. Bucură-te de atmosfera confortabilă în timp ce faci comerț, crești și îți construiești magazinul de vis. Fiecare decizie pe care o iei îți va modela averea și viitorul afacerii tale.",
        "features": [
            "🛍️ Gestionează-ți Magazinul Înființează și organizează propriul tău magazin magic, gestionează-ți inventarul și umple-ți rafturile cu poțiuni, arme magice, cristale misterioase și o varietate de artefacte fantastice. Elaborează strategii pentru expunerile tale pentru a atrage clienți și a asigura profit maxim.",
            "💰 Stăpânește Arta Comerțului Ajustează-ți prețurile dinamic în funcție de cererea și oferta de pe piață și gestionează-ți vânzările. Cu fiecare afacere de succes, averea ta va crește rapid, iar reputația ta se va răspândi în tot regatul. Câștigă încrederea clienților tăi și adaptează-ți strategiile comerciale la nevoile lor în schimbare.",
            "🏰 Devino Cel Mai Bogat Comerciant al Regatului Începe de la o tarabă modestă; în timp, extinde și modernizează-ți magazinul cu noi zone de expunere. Pe măsură ce faima și averea ta cresc, lucrează pentru a deveni cel mai respectat și bogat comerciant din oraș. Construiește-ți imperiul comercial și preia controlul asupra economiei Evului Mediu Fantastic!",
            "🌿 Atmosferă Confortabilă și Relaxantă Relaxează-te și dezvoltă-ți magazinul într-o lume fantastică medievală caldă. Planifică-ți tranzacțiile și găsește-ți propriul ritm. Bucură-te de vibrațiile confortabile în timp ce decizi ce să cumperi, ce să vinzi și cum să faci magazinul tău cel mai bun din oraș. Nu e nicio grabă, dar alegerile tale contează totuși. Concentrează-te pe construirea unei afaceri de succes într-un spațiu în care te poți relaxa cu adevărat."
        ]
    },
    "fi-FI": {
        "name": "Finnish (Finland)",
        "intro": "Arcane Merchant on kaupanhallintasimulaatiopeli, joka sijoittuu keskiaikaisen fantasiavaltakunnan sydämeen. Tutki kaupunkia, tartu kauppamahdollisuuksiin ja aloita matkasi kohti vaurautta. Nauti kodikkaasta tunnelmasta samalla kun käyt kauppaa, kasvat ja rakennat unelmiesi kauppaa. Jokainen tekemäsi päätös muokkaa omaisuuttasi ja yrityksesi tulevaisuutta.",
        "features": [
            "🛍️ Hallitse Kauppaasi Perusta ja järjestä oma taikakauppasi, hallitse varastoasi ja täytä hyllysi taikajuomilla, taika-aseilla, salaperäisillä kristalleilla ja erilaisilla fantastisilla esineillä. Suunnittele esillepanosi houkutellaksesi asiakkaita ja varmistaaksesi maksimaalisen voiton.",
            "💰 Hallitse Kaupankäynnin Taito Säädä hintojasi dynaamisesti markkinoiden kysynnän ja tarjonnan perusteella ja hallitse myyntiäsi. Jokaisen onnistuneen kaupan myötä varallisuutesi kasvaa nopeasti ja maineesi leviää koko valtakuntaan. Ansaitse asiakkaidesi luottamus ja mukauta kauppastrategiasi heidän muuttuviin tarpeisiinsa.",
            "🏰 Tule Valtakunnan Rikkaimmaksi Kauppiaaksi Aloita vaatimattomasta kojusta; ajan myötä laajenna ja päivitä kauppaasi uusilla esittelyalueilla. Kun maineesi ja omaisuutesi kasvavat, pyri tulemaan kaupungin arvostetuimmaksi ja rikkaimmaksi kauppiaaksi. Rakenna kauppaimperiumisi ja ota fantasia-keskiajan talous hallintaasi!",
            "🌿 Kodikas ja Rentouttava Ilmapiiri Rentoudu ja kasvata kauppaasi lämpimässä keskiaikaisessa fantasiamaailmassa. Suunnittele kauppasi ja löydä oma tahtisi. Nauti kodikkaasta tunnelmasta päättäessäsi, mitä ostat, mitä myyt ja miten teet kaupastasi kaupungin parhaan. Ei ole kiirettä, mutta valinnoillasi on silti merkitystä. Keskity rakentamaan menestyvä yritys tilassa, jossa voit todella rentoutua."
        ]
    },
    "tl-PH": {
        "name": "Filipino (Philippines)",
        "intro": "Ang Arcane Merchant ay isang shop management simulation game na itinakda sa puso ng isang medieval fantasy realm. Galugarin ang bayan, samantalahin ang mga pagkakataon sa kalakalan at simulan ang iyong paglalakbay patungo sa kayamanan. Tangkilikin ang maaliwalas na vibes habang nakikipagkalakalan, lumalago at itinatayo ang iyong pangarap na tindahan. Ang bawat desisyong gagawin mo ay huhubog sa iyong kapalaran at sa kinabukasan ng iyong negosyo.",
        "features": [
            "🛍️ Pamahalaan ang Iyong Tindahan Itatag at ayusin ang iyong sariling mahiwagang tindahan, pamahalaan ang iyong imbentaryo at punuin ang iyong mga istante ng mga gayuma, mahiwagang sandata, mahiwagang kristal at iba't ibang kamangha-manghang artifact. Istratehiya ang iyong mga display upang makaakit ng mga customer at matiyak ang maximum na kita.",
            "💰 Kabisaduhin ang Sining ng Kalakalan Ayusin ang iyong mga presyo nang dinamiko batay sa supply at demand sa pamilihan at pamahalaan ang iyong mga benta. Sa bawat matagumpay na deal, ang iyong yaman ay mabilis na lalago at ang iyong reputasyon ay kakalat sa buong kaharian. Makuha ang tiwala ng iyong mga customer at iangkop ang iyong mga diskarte sa kalakalan sa kanilang nagbabagong pangangailangan.",
            "🏰 Maging Pinakamayamang Mangangalakal ng Kaharian Magsimula sa isang hamak na stall; sa paglipas ng panahon, palawakin at i-upgrade ang iyong tindahan gamit ang mga bagong display area. Habang tumataas ang iyong katanyagan at kapalaran, gawin ang iyong paraan upang maging pinaka-respetado at pinakamayamang mangangalakal sa bayan. Buuin ang iyong trading empire at kontrolin ang ekonomiya ng Fantasy Middle Ages!",
            "🌿 Maaliwalas at Nakakarelaks na Kapaligiran Mag-relax at palaguin ang iyong tindahan sa isang mainit na medieval na mundo ng pantasiya. Planuhin ang iyong mga pangangalakal at hanapin ang sarili mong bilis. Tangkilikin ang maaliwalas na vibes habang nagpapasya ka kung ano ang bibilhin, kung ano ang ibebenta at kung paano gagawin ang iyong tindahan na pinakamahusay sa bayan. Walang pagmamadali, ngunit mahalaga pa rin ang iyong mga pagpipilian. Tumutok sa pagbuo ng isang matagumpay na negosyo sa isang puwang kung saan maaari kang tunay na makapagpahinga."
        ]
    },
    "ms-MY": {
        "name": "Malay (Malaysia)",
        "intro": "Arcane Merchant ialah permainan simulasi pengurusan kedai yang berlatarkan di tengah-tengah alam fantasi zaman pertengahan. Terokai bandar, rebut peluang perdagangan dan mulakan perjalanan anda menuju kekayaan. Nikmati suasana yang selesa sambil anda berdagang, berkembang dan membina kedai impian anda. Setiap keputusan yang anda buat akan membentuk nasib anda dan masa depan perniagaan anda.",
        "features": [
            "🛍️ Urus Kedai Anda Tubuhkan dan atur kedai ajaib anda sendiri, urus inventori anda dan isi rak anda dengan ramuan, senjata ajaib, kristal misteri dan pelbagai artifak hebat. Susun strategi paparan anda untuk menarik pelanggan dan memastikan keuntungan maksimum.",
            "💰 Kuasai Seni Perdagangan Laraskan harga anda secara dinamik berdasarkan penawaran dan permintaan di pasaran dan uruskan jualan anda. Dengan setiap perjanjian yang berjaya, kekayaan anda akan berkembang pesat dan reputasi anda akan tersebar di seluruh alam. Dapatkan kepercayaan pelanggan anda dan sesuaikan strategi perdagangan anda dengan keperluan mereka yang berubah-ubah.",
            "🏰 Jadilah Saudagar Terkaya di Kerajaan Mulakan dari gerai yang sederhana; dari masa ke masa, kembangkan dan naik taraf kedai anda dengan kawasan paparan baharu. Apabila kemasyhuran dan kekayaan anda meningkat, berusaha untuk menjadi pedagang yang paling dihormati dan terkaya di bandar. Bina empayar perdagangan anda dan mengawal ekonomi Zaman Pertengahan Fantasi!",
            "🌿 Suasana Selesa dan Santai Bersantai dan kembangkan kedai anda dalam dunia fantasi zaman pertengahan yang hangat. Rancang dagangan anda dan cari rentak anda sendiri. Nikmati suasana yang selesa sambil anda memutuskan perkara yang hendak dibeli, perkara yang hendak dijual dan cara menjadikan kedai anda yang terbaik di bandar. Tidak perlu tergesa-gesa, tetapi pilihan anda tetap penting. Fokus pada membina perniagaan yang berjaya dalam ruang di mana anda benar-benar boleh berehat."
        ]
    },
    "kk-KZ": {
        "name": "Kazakh (Kazakhstan)",
        "intro": "Arcane Merchant — ортағасырлық қиял әлемінің қақ ортасында орнатылған дүкенді басқару симуляциялық ойыны. Қаланы зерттеңіз, сауда мүмкіндіктерін пайдаланыңыз және байлыққа саяхатыңызды бастаңыз. Сауда жасап, өсіп, арманыңыздағы дүкенді құру кезінде жайлы атмосферадан ләззат алыңыз. Сіз қабылдаған әрбір шешім сіздің байлығыңыз бен бизнесіңіздің болашағын қалыптастырады.",
        "features": [
            "🛍️ Дүкеніңізді басқарыңыз Өзіңіздің сиқырлы дүкеніңізді құрыңыз және ұйымдастырыңыз, түгендеуіңізді басқарыңыз және сөрелеріңізді сусындармен, сиқырлы қарулармен, жұмбақ кристалдармен және түрлі ғажайып жәдігерлермен толтырыңыз. Клиенттерді тарту және максималды пайданы қамтамасыз ету үшін дисплейлеріңіздің стратегиясын жасаңыз.",
            "💰 Сауда өнерін меңгеріңіз Нарықтағы сұраныс пен ұсынысқа негізделген бағаларыңызды динамикалық түрде реттеңіз және сатылымдарыңызды басқарыңыз. Әрбір сәтті мәміле арқылы сіздің байлығыңыз тез өседі және сіздің беделіңіз бүкіл әлемге тарайды. Клиенттеріңіздің сеніміне ие болыңыз және сауда стратегияларыңызды олардың өзгермелі қажеттіліктеріне бейімдеңіз.",
            "🏰 Патшалықтың ең бай көпесі болыңыз Қарапайым дүңгіршектен бастаңыз; уақыт өте келе дүкеніңізді жаңа көрсету аймақтарымен кеңейтіңіз және жаңартыңыз. Сіздің атағыңыз бен байлығыңыз артқан сайын, қаладағы ең құрметті және ең бай саудагер болу жолында еңбек етіңіз. Сауда империяңызды құрыңыз және Фантастикалық орта ғасырлар экономикасын бақылауға алыңыз!",
            "🌿 Жайлы және тыныштандыратын атмосфера Жылы ортағасырлық қиял әлемінде демалыңыз және дүкеніңізді өсіріңіз. Сауда-саттықты жоспарлаңыз және өз қарқыныңызды табыңыз. Не сатып алу керектігін, не сату керектігін және дүкеніңізді қаладағы ең жақсы дүкенге қалай айналдыру керектігін шешкен кезде жайлы дірілден ләззат алыңыз. Асығыс жоқ, бірақ сіздің таңдауыңыз әлі де маңызды. Шынымен демалуға болатын кеңістікте табысты бизнес құруға назар аударыңыз."
        ]
    },
    "az-AZ": {
        "name": "Azerbaijani (Azerbaijan)",
        "intro": "Arcane Merchant, orta əsr fantaziya səltənətinin mərkəzində qurulmuş bir dükan idarəetmə simulyasiya oyunudur. Şəhəri kəşf edin, ticarət imkanlarından istifadə edin və sərvətə doğru səyahətinizə başlayın. Ticarət edərkən, böyüyərkən və xəyalınızdakı mağazanı qurarkən rahat ab-havadan həzz alın. Verdiyiniz hər qərar sərvətinizi və işinizin gələcəyini formalaşdıracaq.",
        "features": [
            "🛍️ Mağazanızı İdarə Edin Öz sehrli mağazanızı qurun və təşkil edin, inventarınızı idarə edin və rəflərinizi iksirlər, sehrli silahlar, sirli kristallar və müxtəlif fantastik artefaktlarla doldurun. Müştəriləri cəlb etmək və maksimum qazanc əldə etmək üçün vitrinlərinizin strategiyasını qurun.",
            "💰 Ticarət Sənətinə Yiyələnin Qiymətlərinizi bazardakı tələb və təklifə əsasən dinamik olaraq tənzimləyin və satışlarınızı idarə edin. Hər uğurlu sövdələşmə ilə sərvətiniz sürətlə artacaq və nüfuzunuz bütün səltənətə yayılacaq. Müştərilərinizin etibarını qazanın və ticarət strategiyalarınızı onların dəyişən ehtiyaclarına uyğunlaşdırın.",
            "🏰 Krallığın Ən Zəngin Taciri Olun Təvazökar bir piştaxtadan başlayın; zaman keçdikcə mağazanızı yeni nümayiş sahələri ilə genişləndirin və təkmilləşdirin. Şöhrətiniz və sərvətiniz artdıqca, şəhərin ən hörmətli və ən zəngin taciri olmaq yolunda çalışın. Ticarət imperiyanızı qurun və Fantaziya Orta Əsrlərinin iqtisadiyyatını nəzarətə götürün!",
            "🌿 Rahat və Rahatlaşdırıcı Atmosfer İsti orta əsr fantaziya dünyasında dincəlin və mağazanızı böyüdün. Ticarətinizi planlaşdırın və öz tempinizi tapın. Nə alacağınıza, nə satacağınıza və mağazanızı şəhərin ən yaxşısı halına necə gətirəcəyinizə qərar verərkən rahat ab-havadan həzz alın. Tələsmək yoxdur, amma seçimləriniz yenə də önəmlidir. Həqiqətən dincələ biləcəyiniz bir məkanda uğurlu bir iş qurmağa diqqət yetirin."
        ]
    },
    "af-ZA": {
        "name": "Afrikaans (South Africa)",
        "intro": "Arcane Merchant is 'n winkelbestuursimulasiespeletjie wat in die hart van 'n middeleeuse fantasieryk afspeel. Verken die dorp, gryp handelsgeleenthede aan en begin jou reis na rykdom. Geniet die gesellige atmosfeer terwyl jy handel dryf, groei en jou droomwinkel bou. Elke besluit wat jy neem sal jou fortuin en die toekoms van je besigheid vorm.",
        "features": [
            "🛍️ Bestuur Jou Winkel Vestig en organiseer jou eie magiese winkel, bestuur jou voorraad en vul jou rakke met drankies, magiese wapens, geheimsinnige kristalle en 'n verskeidenheid fantastiese artefakte. Strategiseer jou uitstallings om kliënte te lok en maksimum wins te verseker.",
            "💰 Meester die Kuns van Handel Pas jou pryse dinamies aan op grond van vraag en aanbod in die mark en bestuur jou verkopen. Met elke suksesvolle transaksie sal jou rykdom vinnig groei en jou reputasie sal deur die hele ryk versprei. Verdien die vertroue van jou kliënte en pas jou handelstrategieë aan by hul veranderende behoeftes.",
            "🏰 Word die Rykste Handelaar van die Koninkryk Begin by 'n nederige stalletjie; met verloop van tyd, brei uit en gradeer jou winkel op met nuwe vertoonareas. Soos jou roem en fortuin styg, werk jou pad op om die mees gerespekteerde en rykste handelaar in die dorp te word. Bou jou handelsryk en neem beheer oor die ekonomie van die Fantasie Middeleeue!",
            "🌿 Gesellige en Ontspannende Atmosfeer Ontspan en laat jou winkel groei in 'n warm middeleeuse fantasiewêreld. Beplan jou ambagte en vind jou eie pas. Geniet die gesellige atmosfeer terwyl jy besluit wat om te koop, wat om te verkoop en hoe om jou winkel die beste in die dorp te maak. Daar is geen haas nie, maar jou keuses maak steeds saak. Fokus daarop om 'n suksesvolle besigheid te bou in 'n ruimte waar jy werklik kan ontspan."
        ]
    }
};